require('config.clipboard')
require('config.opts')
require('config.keys')
require('config.lsp')
require('config.plugins')
require('config.colorscheme')
require('config.terminal')
require('config.open_url_from_win_browser_from_wsl')
