vim.opt.termguicolors = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 2
vim.opt.syntax = 'on'
vim.opt.number = true
vim.opt.encoding = 'utf-8'
vim.opt.mouse = 'a'
vim.opt.title = true
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.list = true
vim.opt.listchars = {
    tab='-»',
    space = '·',
    -- eol='↲',
    --trail='-',
    --extends='»', 
    --precedes='«', 
    --nbsp='%',
}
vim.opt.expandtab = true
vim.opt.cursorline = true
vim.opt.cursorcolumn = false -- preview floatingとかぶって見えにくくなるのでfase
vim.opt.background = "light"
